### ISSUE TITLE
Cannon compile no ptp.h file

### ISSUE THREAD

**Issue by ghost** [yifanlu/VitaMTP#14]
When I try and compile this, it says the ptp.h file is not there, when it actually is.
Here's the terminal output:

make  all-recursive
make[1]: Entering directory `/home/smoke/Desktop/VitaMTP'
Making all in src
make[2]: Entering directory`/home/smoke/Desktop/VitaMTP/src'
gcc -DHAVE_CONFIG_H -I. -I..    -I/usr/include/libusb-1.0   -std=c99 -g -O2 -MT libvitamtp_a-vitamtp.o -MD -MP -MF .deps/libvitamtp_a-vitamtp.Tpo -c -o libvitamtp_a-vitamtp.o `test -f 'vitamtp.c' || echo './'`vitamtp.c
vitamtp.c:23:17: fatal error: ptp.h: No such file or directory
compilation terminated.
make[2]: **\* [libvitamtp_a-vitamtp.o] Error 1
make[2]: Leaving directory `/home/smoke/Desktop/VitaMTP/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/home/smoke/Desktop/VitaMTP'
make: **\* [all] Error 2

EDIT:
Actually, I just checked again, and there's no ptp.h file at all even the zip I downloaded

**Comment by gokuhs** [comment]
+1, i have the same problem.

**Comment by yifanlu** [comment]
Type in

> pkg-config --libs libmtp

in your command prompt. If any error shows up, you didn't install the custom libmtp correctly.

**Comment by gokuhs** [comment]
I taken up again the project and still the same:

I try you suggestion and this is the output:

```
gokuhs-server-OnLine:~# pkg-config libmtp
gokuhs-server-OnLine:~#
```

And again try to compile: 

```
gokuhs-server-OnLine:~$  ./autogen.sh
```

(no errors)

```
 gokuhs-server-OnLine:~$ ./configure
```

(without errors)

```
gokuhs-server-OnLine:~$ make
make  all-recursive
make[1]: se ingresa al directorio `/home/gokuh/VitaMTP/VitaMTP'
Making all in src
make[2]: se ingresa al directorio `/home/gokuh/VitaMTP/VitaMTP/src'
gcc -DHAVE_CONFIG_H -I. -I..    -I/usr/include/libusb-1.0   -std=c99 -g -O2 -MT libvitamtp_a-vitamtp.o -MD -MP -MF .deps/libvitamtp_a-vitamtp.Tpo -c -o libvitamtp_a-vitamtp.o `test -f 'vitamtp.c' || echo './'`vitamtp.c
vitamtp.c:23:17: fatal error: ptp.h: No existe el fichero o el directorio
compilation terminated.
make[2]: *** [libvitamtp_a-vitamtp.o] Error 1
make[2]: se sale del directorio `/home/gokuh/VitaMTP/VitaMTP/src'
make[1]: *** [all-recursive] Error 1
make[1]: se sale del directorio `/home/gokuh/VitaMTP/VitaMTP'
make: *** [all] Error 2
```

**EDIT**

I try to search the header "ptp.h" but i don't find the file: 

```
gokuhs-server-OnLine:/usr/include# find / -name 'ptp.h'
gokuhs-server-OnLine:/usr/include#
```

You really ptp.h is included in libmtp package?

Thanks!

**Comment by yifanlu** [comment]
If you are using my libmtp and installed it correctly, then yes. See https://github.com/yifanlu/libMTP/blob/master/src/Makefile.am there is a line that includes ptp.h

> pkg-config --version libmtp

should return

> 0.27.1

If not, try running make install again on libmtp and see what happens.
