### ISSUE TITLE
Libxml2 issues

### ISSUE THREAD

**Issue by theredbaron1834** [yifanlu/VitaMTP#15]
Compiling fails with 

gcc -DHAVE_CONFIG_H -I. -I..    -I/usr/local/include -I/usr/include/libusb-1.0   -std=c99 -g -O2 -MT libvitamtp_a-xmlparsing.o -MD -MP -MF .deps/libvitamtp_a-xmlparsing.Tpo -c -o libvitamtp_a-xmlparsing.o `test -f 'xmlparsing.c' || echo './'`xmlparsing.c
xmlparsing.c:23:30: fatal error: libxml/xmlmemory.h: No such file or directory
compilation terminated.

I am running Ubuntu 12.10, with Libxml2-dev installed. If I look through the deb, it shows that xmlmemory.h is in fact installed to /usr/include/libxml2/libxml/xmlmemory.h. I tried linking /usr/include/libxml2/libxml/ to /lib/, and that didn't work. That is about as far as I can go on this. :)

**Comment by yifanlu** [comment]
https://github.com/yifanlu/VitaMTP/wiki/Compiling-on-Linux
