### ISSUE TITLE
Fix compiling and issues on Linux.

### ISSUE THREAD

**Issue by codestation** [yifanlu/VitaMTP#18]
I found some problems while trying to compile vitamtp/opencma:
- libxml2 include location isn't included in the Makefile.
- The use of c99 and gcc causes some problems when using structures from signal.h
- Some includes where missing.

I fixed these in the attached patch. I also removed the internal libmtp reference from the .pc file since i am linking statically to your fork of libmtp (because installing your copy causes a conflict with the system copy of libmtp included in various linux distros).

I don't know much of auto ~~hell~~ tools so i don't know if the libxml2 patch is correct. I also suggest that your fork of libmtp is compiled statically aganist libvitamtp (at least until your changes goes to upstream). I don't know how to make it with auto ~~hell~~ tools so i had to do it in the configure step manually (You can see it in here: https://aur.archlinux.org/packages/vi/vitamtp-git/PKGBUILD)

Patch fle: https://gist.github.com/codestation/5500223

opencma needs root access on linux since libusb doesn't have access to the raw usb devices by default. One way to fix this is to create a custom udev rule that detect the Vita and change the permissions for the node.

This file can be installed on $(pkg-config --variable=udevdir udev)/rules.d/ and udev takes care of the rest.
https://gist.github.com/codestation/5500244

**Comment by yifanlu** [comment]
Thank you.

**Comment by yifanlu** [comment]
Added to latest commit.
