### ISSUE TITLE
Vita -> PC transfers fail on linux (fedora17)

### ISSUE THREAD

**Issue by yosh778** [yifanlu/VitaMTP#2]
Command line logs stop right after the connection logs, and then when transferring games/saves from Vita to PC a segmentation fault occurs.

**Comment by yifanlu** [comment]
What's the output when running opencma with the -l 6 option?

**Comment by yosh778** [comment]
pmed it to you, however then I upgraded the code to your latest commits, and the issue is now already solved !
I guess it was probably just because folders weren't created correctly before.
