### ISSUE TITLE
Error (C3-14978-9)

### ISSUE THREAD

**Issue by ghost** [yifanlu/VitaMTP#20]
I get error (C3-14978-9) when I start the CMA app on my Vita
Heres the output:

smoke@smoke:~$ sudo opencma -u "/home/smoke/PSVita/" -p "/home/smoke/Pictures/" -v "/home/smoke/Videos/" -m "/home/smoke/Music/" -a "/home/smoke/PSVita/" -l 4
[sudo] password for smoke:
OpenCMA 1.0 Beta
libVitaMTP Version: 1.1
Protocol Max Version: 01500010
Once connected, send SIGTSTP (usually Ctrl+Z) to refresh the database.
main: Waiting for Vita to connect...
PTP: Opening session
VitaMTP ptp_usb_sendreq[519]: REQUEST: 0x1002, Open session
VitaMTP ptp_write_func[341]: USB OUT==>
00: 10 00 00 00 01 00 02 10 00 00 00 00 01 00 00 00 | ................
VitaMTP ptp_usb_getresp[801]: RESPONSE: VitaMTP ptp_read_func[199]: Remaining size to read: 0x0200 bytes
VitaMTP ptp_read_func[218]: Reading in 0x0200 bytes
VitaMTP ptp_read_func[227]: Result of read: 0x0000 (12 bytes)
VitaMTP ptp_read_func[232]: <==USB IN
0: 0C 00 00 00 03 00 01 20 00 00 00 00             | ....... ....  
VitaMTP ptp_usb_getresp[828]: 2001
main: Vita connected: serial XXXXXXXXXXXXXXXXX
VitaMTP ptp_usb_sendreq[519]: REQUEST: 0x9511, Unknown (9511)
VitaMTP ptp_write_func[341]: USB OUT==>
0: 0C 00 00 00 01 00 11 95 01 00 00 00             | ............  
VitaMTP ptp_usb_getdata[656]: GET DATA PHASE
VitaMTP ptp_read_func[199]: Remaining size to read: 0x0200 bytes
VitaMTP ptp_read_func[218]: Reading in 0x0200 bytes
VitaMTP ptp_read_func[227]: Result of read: 0x0000 (425 bytes)
VitaMTP ptp_read_func[232]: <==USB IN
000: A9 01 00 00 02 00 11 95 01 00 00 00 99 01 00 00 | ................
010: 3C 56 49 54 41 49 6E 66 6F 72 6D 61 74 69 6F 6E | <VITAInformation
020: 20 72 65 73 70 6F 6E 64 65 72 56 65 72 73 69 6F |  responderVersio
030: 6E 3D 22 32 2E 31 31 22 20 70 72 6F 74 6F 63 6F | n="2.11" protoco
040: 6C 56 65 72 73 69 6F 6E 3D 22 30 31 35 30 30 30 | lVersion="015000
050: 31 30 22 20 6F 6E 6C 69 6E 65 49 64 3D 22 53 4D | 10" onlineId="SM
060: 4F 4B 45 36 34 32 32 33 34 22 20 6D 6F 64 65 6C | OKE642234" model
070: 49 6E 66 6F 3D 22 50 43 48 30 31 30 30 31 5A 41 | Info="PCH01001ZA
080: 30 31 22 20 74 69 6D 65 7A 6F 6E 65 3D 22 31 32 | 01" timezone="12
090: 22 3E 3C 70 68 6F 74 6F 54 68 75 6D 62 20 74 79 | "><photoThumb ty
0A0: 70 65 3D 22 30 22 20 63 6F 64 65 63 54 79 70 65 | pe="0" codecType
0B0: 3D 22 31 37 22 20 77 69 64 74 68 3D 22 32 31 33 | ="17" width="213
0C0: 22 20 68 65 69 67 68 74 3D 22 31 32 30 22 2F 3E | " height="120"/>
0D0: 3C 76 69 64 65 6F 54 68 75 6D 62 20 74 79 70 65 | <videoThumb type
0E0: 3D 22 31 22 20 63 6F 64 65 63 54 79 70 65 3D 22 | ="1" codecType="
0F0: 35 22 20 77 69 64 74 68 3D 22 32 31 33 22 20 68 | 5" width="213" h
100: 65 69 67 68 74 3D 22 31 32 30 22 20 64 75 72 61 | eight="120" dura
110: 74 69 6F 6E 3D 22 31 35 22 2F 3E 3C 6D 75 73 69 | tion="15"/><musi
120: 63 54 68 75 6D 62 20 74 79 70 65 3D 22 30 22 20 | cThumb type="0"
130: 63 6F 64 65 63 54 79 70 65 3D 22 31 37 22 20 77 | codecType="17" w
140: 69 64 74 68 3D 22 31 39 32 22 20 68 65 69 67 68 | idth="192" heigh
150: 74 3D 22 31 39 32 22 2F 3E 3C 67 61 6D 65 54 68 | t="192"/><gameTh
160: 75 6D 62 20 74 79 70 65 3D 22 30 22 20 63 6F 64 | umb type="0" cod
170: 65 63 54 79 70 65 3D 22 31 37 22 20 77 69 64 74 | ecType="17" widt
180: 68 3D 22 31 39 32 22 20 68 65 69 67 68 74 3D 22 | h="192" height="
190: 31 39 32 22 2F 3E 3C 2F 56 49 54 41 49 6E 66 6F | 192"/></VITAInfo
1A0: 72 6D 61 74 69 6F 6E 3E 00                      | rmation>.  
VitaMTP ptp_usb_getresp[801]: RESPONSE: VitaMTP ptp_read_func[199]: Remaining size to read: 0x0200 bytes
VitaMTP ptp_read_func[218]: Reading in 0x0200 bytes
VitaMTP ptp_read_func[227]: Result of read: 0x0000 (12 bytes)
VitaMTP ptp_read_func[232]: <==USB IN
0: 0C 00 00 00 03 00 01 20 01 00 00 00             | ....... ....  
VitaMTP ptp_usb_getresp[828]: 2001
VitaMTP ptp_usb_sendreq[519]: REQUEST: 0x951c, Unknown (951c)
VitaMTP ptp_write_func[341]: USB OUT==>
0: 0C 00 00 00 01 00 1C 95 02 00 00 00             | ............  
VitaMTP ptp_usb_senddata[567]: SEND DATA PHASE
VitaMTP ptp_write_func[341]: USB OUT==>
00: DB 00 00 00 02 00 1C 95 02 00 00 00 CB 00 00 00 | ................
10: 3C 3F 78 6D 6C 20 76 65 72 73 69 6F 6E 3D 22 31 | <?xml version="1
20: 2E 30 22 20 65 6E 63 6F 64 69 6E 67 3D 22 55 54 | .0" encoding="UT
30: 46 2D 38 22 3F 3E 0A 3C 69 6E 69 74 69 61 74 6F | F-8"?>.<initiato
40: 72 49 6E 66 6F 20 70 6C 61 74 66 6F 72 6D 54 79 | rInfo platformTy
50: 70 65 3D 22 50 43 22 20 70 6C 61 74 66 6F 72 6D | pe="PC" platform
60: 53 75 62 74 79 70 65 3D 22 55 6E 6B 6E 6F 77 6E | Subtype="Unknown
70: 22 20 6F 73 56 65 72 73 69 6F 6E 3D 22 30 2E 30 | " osVersion="0.0
80: 22 20 76 65 72 73 69 6F 6E 3D 22 31 2E 31 22 20 | " version="1.1"
90: 70 72 6F 74 6F 63 6F 6C 56 65 72 73 69 6F 6E 3D | protocolVersion=
A0: 22 30 31 35 30 30 30 31 30 22 20 6E 61 6D 65 3D | "01500010" name=
B0: 22 4F 70 65 6E 43 4D 41 20 31 2E 30 20 42 65 74 | "OpenCMA 1.0 Bet
C0: 61 22 20 61 70 70 6C 69 63 61 74 69 6F 6E 54 79 | a" applicationTy
D0: 70 65 3D 22 35 22 20 2F 3E 0A 00                | pe="5" />..  
VitaMTP ptp_usb_getresp[801]: RESPONSE: VitaMTP ptp_read_func[199]: Remaining size to read: 0x0200 bytes
VitaMTP ptp_read_func[218]: Reading in 0x0200 bytes
VitaMTP ptp_read_func[227]: Result of read: 0x0000 (16 bytes)
VitaMTP ptp_read_func[232]: <==USB IN
00: 10 00 00 00 03 00 01 20 02 00 00 00 00 00 00 00 | ....... ........
VitaMTP ptp_usb_getresp[828]: 2001
VitaMTP ptp_usb_sendreq[519]: REQUEST: 0x953b, Unknown (953b)
VitaMTP ptp_write_func[341]: USB OUT==>
0: 0C 00 00 00 01 00 3B 95 03 00 00 00             | ......;.....  
VitaMTP ptp_usb_getdata[656]: GET DATA PHASE
VitaMTP ptp_read_func[199]: Remaining size to read: 0x0200 bytes
VitaMTP ptp_read_func[218]: Reading in 0x0200 bytes
VitaMTP ptp_read_func[227]: Result of read: 0x0000 (512 bytes)
VitaMTP ptp_read_func[232]: <==USB IN
000: C2 04 00 00 02 00 3B 95 03 00 00 00 B2 04 00 00 | ......;.........
010: 3C 3F 78 6D 6C 20 76 65 72 73 69 6F 6E 3D 22 31 | <?xml version="1
020: 2E 30 22 20 65 6E 63 6F 64 69 6E 67 3D 22 55 54 | .0" encoding="UT
030: 46 2D 38 22 3F 3E 3C 63 61 70 61 62 69 6C 69 74 | F-8"?><capabilit
040: 79 49 6E 66 6F 20 76 65 72 73 69 6F 6E 3D 22 31 | yInfo version="1
050: 2E 30 22 3E 3C 66 75 6E 63 74 69 6F 6E 20 74 79 | .0"><function ty
060: 70 65 3D 22 70 68 6F 74 6F 22 3E 3C 66 6F 72 6D | pe="photo"><form
070: 61 74 20 63 6F 6E 74 65 6E 74 54 79 70 65 3D 22 | at contentType="
080: 69 6D 61 67 65 2F 6A 70 65 67 22 20 2F 3E 3C 66 | image/jpeg" /><f
090: 6F 72 6D 61 74 20 63 6F 6E 74 65 6E 74 54 79 70 | ormat contentTyp
0A0: 65 3D 22 69 6D 61 67 65 2F 70 6E 67 22 20 2F 3E | e="image/png" />
0B0: 3C 66 6F 72 6D 61 74 20 63 6F 6E 74 65 6E 74 54 | <format contentT
0C0: 79 70 65 3D 22 69 6D 61 67 65 2F 74 69 66 66 22 | ype="image/tiff"
0D0: 20 2F 3E 3C 66 6F 72 6D 61 74 20 63 6F 6E 74 65 |  /><format conte
0E0: 6E 74 54 79 70 65 3D 22 69 6D 61 67 65 2F 62 6D | ntType="image/bm
0F0: 70 22 20 2F 3E 3C 66 6F 72 6D 61 74 20 63 6F 6E | p" /><format con
100: 74 65 6E 74 54 79 70 65 3D 22 69 6D 61 67 65 2F | tentType="image/
110: 67 69 66 22 20 2F 3E 3C 66 6F 72 6D 61 74 20 63 | gif" /><format c
120: 6F 6E 74 65 6E 74 54 79 70 65 3D 22 69 6D 61 67 | ontentType="imag
130: 65 2F 78 2D 6D 70 6F 22 20 2F 3E 3C 66 6F 72 6D | e/x-mpo" /><form
140: 61 74 20 63 6F 6E 74 65 6E 74 54 79 70 65 3D 22 | at contentType="
150: 76 69 64 65 6F 2F 78 2D 70 68 6F 74 6F 63 61 6D | video/x-photocam
160: 2D 6D 6F 76 69 65 22 20 2F 3E 3C 6F 70 74 69 6F | -movie" /><optio
170: 6E 20 6E 61 6D 65 3D 22 70 68 79 73 69 63 61 6C | n name="physical
180: 56 69 65 77 22 20 2F 3E 3C 2F 66 75 6E 63 74 69 | View" /></functi
190: 6F 6E 3E 3C 66 75 6E 63 74 69 6F 6E 20 74 79 70 | on><function typ
1A0: 65 3D 22 6D 75 73 69 63 22 3E 3C 66 6F 72 6D 61 | e="music"><forma
1B0: 74 20 63 6F 6E 74 65 6E 74 54 79 70 65 3D 22 61 | t contentType="a
1C0: 75 64 69 6F 2F 6D 70 33 22 20 2F 3E 3C 66 6F 72 | udio/mp3" /><for
1D0: 6D 61 74 20 63 6F 6E 74 65 6E 74 54 79 70 65 3D | mat contentType=
1E0: 22 61 75 64 69 6F 2F 6D 70 34 22 20 63 6F 64 65 | "audio/mp4" code
1F0: 63 3D 22 41 41 43 22 20 2F 3E 3C 66 6F 72 6D 61 | c="AAC" /><forma
VitaMTP ptp_read_func[199]: Remaining size to read: 0x02c2 bytes
VitaMTP ptp_read_func[218]: Reading in 0x02c2 bytes
VitaMTP ptp_read_func[227]: Result of read: 0x0000 (706 bytes)
VitaMTP ptp_read_func[232]: <==USB IN
000: 74 20 63 6F 6E 74 65 6E 74 54 79 70 65 3D 22 61 | t contentType="a
010: 75 64 69 6F 2F 77 61 76 22 20 63 6F 64 65 63 3D | udio/wav" codec=
020: 22 4C 50 43 4D 22 20 2F 3E 3C 6F 70 74 69 6F 6E | "LPCM" /><option
030: 20 6E 61 6D 65 3D 22 70 6C 61 79 6C 69 73 74 22 |  name="playlist"
040: 20 2F 3E 3C 2F 66 75 6E 63 74 69 6F 6E 3E 3C 66 |  /></function><f
050: 75 6E 63 74 69 6F 6E 20 74 79 70 65 3D 22 76 69 | unction type="vi
060: 64 65 6F 22 3E 3C 66 6F 72 6D 61 74 20 63 6F 6E | deo"><format con
070: 74 65 6E 74 54 79 70 65 3D 22 76 69 64 65 6F 2F | tentType="video/
080: 6D 70 34 22 20 76 69 64 65 6F 43 6F 64 65 63 3D | mp4" videoCodec=
090: 22 4D 50 45 47 34 22 20 61 75 64 69 6F 43 6F 64 | "MPEG4" audioCod
0A0: 65 63 3D 22 41 41 43 22 20 2F 3E 3C 66 6F 72 6D | ec="AAC" /><form
0B0: 61 74 20 63 6F 6E 74 65 6E 74 54 79 70 65 3D 22 | at contentType="
0C0: 76 69 64 65 6F 2F 6D 70 34 22 20 76 69 64 65 6F | video/mp4" video
0D0: 43 6F 64 65 63 3D 22 41 56 43 22 20 61 75 64 69 | Codec="AVC" audi
0E0: 6F 43 6F 64 65 63 3D 22 41 41 43 22 20 2F 3E 3C | oCodec="AAC" /><
0F0: 66 6F 72 6D 61 74 20 63 6F 6E 74 65 6E 74 54 79 | format contentTy
100: 70 65 3D 22 76 69 64 65 6F 2F 78 2D 6D 61 72 6C | pe="video/x-marl
110: 69 6E 2D 65 73 74 22 20 2F 3E 3C 66 6F 72 6D 61 | in-est" /><forma
120: 74 20 63 6F 6E 74 65 6E 74 54 79 70 65 3D 22 76 | t contentType="v
130: 69 64 65 6F 2F 78 2D 6D 61 72 6C 69 6E 2D 76 6F | ideo/x-marlin-vo
140: 64 22 20 2F 3E 3C 6F 70 74 69 6F 6E 20 6E 61 6D | d" /><option nam
150: 65 3D 22 70 68 79 73 69 63 61 6C 56 69 65 77 22 | e="physicalView"
160: 20 2F 3E 3C 2F 66 75 6E 63 74 69 6F 6E 3E 3C 66 |  /></function><f
170: 75 6E 63 74 69 6F 6E 20 74 79 70 65 3D 22 67 61 | unction type="ga
180: 6D 65 22 3E 3C 66 6F 72 6D 61 74 20 63 6F 6E 74 | me"><format cont
190: 65 6E 74 54 79 70 65 3D 22 76 69 74 61 41 70 70 | entType="vitaApp
1A0: 22 20 2F 3E 3C 66 6F 72 6D 61 74 20 63 6F 6E 74 | " /><format cont
1B0: 65 6E 74 54 79 70 65 3D 22 50 53 50 47 61 6D 65 | entType="PSPGame
1C0: 22 20 2F 3E 3C 66 6F 72 6D 61 74 20 63 6F 6E 74 | " /><format cont
1D0: 65 6E 74 54 79 70 65 3D 22 50 53 50 53 61 76 65 | entType="PSPSave
1E0: 44 61 74 61 22 20 2F 3E 3C 66 6F 72 6D 61 74 20 | Data" /><format
1F0: 63 6F 6E 74 65 6E 74 54 79 70 65 3D 22 50 53 47 | contentType="PSG
200: 61 6D 65 22 20 2F 3E 3C 66 6F 72 6D 61 74 20 63 | ame" /><format c
210: 6F 6E 74 65 6E 74 54 79 70 65 3D 22 50 53 4D 41 | ontentType="PSMA
220: 70 70 22 20 2F 3E 3C 2F 66 75 6E 63 74 69 6F 6E | pp" /></function
230: 3E 3C 66 75 6E 63 74 69 6F 6E 20 74 79 70 65 3D | ><function type=
240: 22 62 61 63 6B 75 70 22 3E 3C 66 6F 72 6D 61 74 | "backup"><format
250: 20 74 79 70 65 3D 22 73 79 73 74 65 6D 42 61 63 |  type="systemBac
260: 6B 75 70 22 20 2F 3E 3C 2F 66 75 6E 63 74 69 6F | kup" /></functio
270: 6E 3E 3C 66 75 6E 63 74 69 6F 6E 20 74 79 70 65 | n><function type
280: 3D 22 73 79 73 74 65 6D 55 70 64 61 74 65 22 20 | ="systemUpdate"
290: 2F 3E 3C 66 75 6E 63 74 69 6F 6E 20 74 79 70 65 | /><function type
2A0: 3D 22 6E 65 74 77 6F 72 6B 52 70 63 22 20 2F 3E | ="networkRpc" />
2B0: 3C 2F 63 61 70 61 62 69 6C 69 74 79 49 6E 66 6F | </capabilityInfo
2C0: 3E 00                                           | >.  
VitaMTP ptp_usb_getresp[801]: RESPONSE: VitaMTP ptp_read_func[199]: Remaining size to read: 0x0200 bytes
VitaMTP ptp_read_func[218]: Reading in 0x0200 bytes
VitaMTP ptp_read_func[227]: Result of read: 0x0000 (12 bytes)
VitaMTP ptp_read_func[232]: <==USB IN
0: 0C 00 00 00 03 00 01 20 03 00 00 00             | ....... ....  
VitaMTP ptp_usb_getresp[828]: 2001
VitaMTP: Vita capability info: <?xml version="1.0" encoding="UTF-8"?><capabilityInfo version="1.0"><function type="photo"><format contentType="image/jpeg" /><format contentType="image/png" /><format contentType="image/tiff" /><format contentType="image/bmp" /><format contentType="image/gif" /><format contentType="image/x-mpo" /><format contentType="video/x-photocam-movie" /><option name="physicalView" /></function><function type="music"><format contentType="audio/mp3" /><format contentType="audio/mp4" codec="AAC" /><format contentType="audio/wav" codec="LPCM" /><option name="playlist" /></function><function type="video"><format contentType="video/mp4" videoCodec="MPEG4" audioCodec="AAC" /><format contentType="video/mp4" videoCodec="AVC" audioCodec="AAC" /><format contentType="video/x-marlin-est" /><format contentType="video/x-marlin-vod" /><option name="physicalView" /></function><function type="game"><format contentType="vitaApp" /><format contentType="PSPGame" /><format contentType="PSPSaveData" /><format contentType="PSGame" /><format contentType="PSMApp" /></function><function type="backup"><format type="systemBackup" /></function><function type="systemUpdate" /><function type="networkRpc" /></capabilityInfo>
VitaMTP ptp_usb_sendreq[519]: REQUEST: 0x953c, Unknown (953c)
VitaMTP ptp_write_func[341]: USB OUT==>
0: 0C 00 00 00 01 00 3C 95 04 00 00 00             | ......<.....  
VitaMTP ptp_usb_senddata[567]: SEND DATA PHASE
VitaMTP ptp_write_func[341]: USB OUT==>
00: 66 00 00 00 02 00 3C 95 04 00 00 00 56 00 00 00 | f.....<.....V...
10: 3C 3F 78 6D 6C 20 76 65 72 73 69 6F 6E 3D 22 31 | <?xml version="1
20: 2E 30 22 20 65 6E 63 6F 64 69 6E 67 3D 22 55 54 | .0" encoding="UT
30: 46 2D 38 22 3F 3E 3C 63 61 70 61 62 69 6C 69 74 | F-8"?><capabilit
40: 79 49 6E 66 6F 20 76 65 72 73 69 6F 6E 3D 22 31 | yInfo version="1
50: 2E 30 22 3E 3C 2F 63 61 70 61 62 69 6C 69 74 79 | .0"></capability
60: 49 6E 66 6F 3E 00                               | Info>.  
VitaMTP ptp_usb_getresp[801]: RESPONSE: VitaMTP ptp_read_func[199]: Remaining size to read: 0x0200 bytes
VitaMTP ptp_read_func[218]: Reading in 0x0200 bytes
VitaMTP ptp_read_func[227]: Result of read: 0x0000 (16 bytes)
VitaMTP ptp_read_func[232]: <==USB IN
00: 10 00 00 00 03 00 01 20 04 00 00 00 00 00 00 00 | ....... ........
VitaMTP ptp_usb_getresp[828]: 2001
VitaMTP ptp_usb_sendreq[519]: REQUEST: 0x952a, Unknown (952a)
VitaMTP ptp_write_func[341]: USB OUT==>
00: 10 00 00 00 01 00 2A 95 05 00 00 00 00 00 00 00 | ......*.........
VitaMTP ptp_usb_getresp[801]: RESPONSE: VitaMTP ptp_read_func[199]: Remaining size to read: 0x0200 bytes
VitaMTP ptp_read_func[218]: Reading in 0x0200 bytes
VitaMTP ptp_read_func[227]: Result of read: 0x0000 (12 bytes)
VitaMTP ptp_read_func[232]: <==USB IN
0: 0C 00 00 00 03 00 01 20 05 00 00 00             | ....... ....  
VitaMTP ptp_usb_getresp[828]: 2001
vitaEventListener: Event 0xC10B recieved, slot 7 with function address 0x804a22a
vitaEventSendHttpObjectFromURL: Event recieved: RequestSendHttpObjectFromURL, code: 0xc10b, id: 1
VitaMTP ptp_usb_sendreq[519]: REQUEST: 0x951f, Unknown (951f)
VitaMTP ptp_write_func[341]: USB OUT==>
00: 10 00 00 00 01 00 1F 95 06 00 00 00 01 00 00 00 | ................
VitaMTP ptp_usb_getdata[656]: GET DATA PHASE
VitaMTP ptp_read_func[199]: Remaining size to read: 0x0200 bytes
VitaMTP ptp_read_func[218]: Reading in 0x0200 bytes
VitaMTP ptp_read_func[227]: Result of read: 0x0000 (193 bytes)
VitaMTP ptp_read_func[232]: <==USB IN
00: C1 00 00 00 02 00 1F 95 06 00 00 00 00 00 00 00 | ................
10: 00 00 00 00 A9 00 00 00 68 74 74 70 3A 2F 2F 66 | ........http://f
20: 75 73 30 31 2E 70 73 70 32 2E 75 70 64 61 74 65 | us01.psp2.update
30: 2E 70 6C 61 79 73 74 61 74 69 6F 6E 2E 6E 65 74 | .playstation.net
40: 2F 75 70 64 61 74 65 2F 70 73 70 32 2F 6C 69 73 | /update/psp2/lis
50: 74 2F 75 73 2F 70 73 70 32 2D 75 70 64 61 74 65 | t/us/psp2-update
60: 6C 69 73 74 2E 78 6D 6C 3F 76 65 72 3D 30 32 31 | list.xml?ver=021
70: 31 30 30 30 30 26 73 69 64 3D 34 39 35 37 39 65 | 10000&sid=49579e
80: 61 61 34 39 37 66 66 62 31 66 36 35 65 36 30 33 | aa497ffb1f65e603
90: 65 36 30 61 34 32 66 65 31 35 36 38 31 62 64 62 | e60a42fe15681bdb
A0: 39 37 63 30 65 32 35 62 35 61 38 34 34 32 66 65 | 97c0e25b5a8442fe
B0: 36 31 66 64 38 62 31 37 31 34 26 6E 64 3D 30 3B | 61fd8b1714&nd=0;
C0: 00                                              | .  
VitaMTP ptp_usb_getresp[801]: RESPONSE: VitaMTP ptp_read_func[199]: Remaining size to read: 0x0200 bytes
VitaMTP ptp_read_func[218]: Reading in 0x0200 bytes
VitaMTP ptp_read_func[227]: Result of read: 0x0000 (12 bytes)
VitaMTP ptp_read_func[232]: <==USB IN
0: 0C 00 00 00 03 00 01 20 06 00 00 00             | ....... ....  
VitaMTP ptp_usb_getresp[828]: 2001
requestURL: Reading of /home/smoke/PSVita//psp2-updatelist.xml returned 0.
vitaEventSendHttpObjectFromURL: Sending 963d bytes of data for HTTP request http://fus01.psp2.update.playstation.net/update/psp2/list/us/psp2-updatelist.xml?ver=02110000&sid=49579eaa497ffb1f65e603e60a42fe15681bdb97c0e25b5a8442fe61fd8b1714&nd=0;
VitaMTP ptp_usb_sendreq[519]: REQUEST: 0x9520, Unknown (9520)
VitaMTP ptp_write_func[341]: USB OUT==>
00: 10 00 00 00 01 00 20 95 07 00 00 00 01 00 00 00 | ...... .........
VitaMTP ptp_usb_senddata[567]: SEND DATA PHASE
VitaMTP ptp_write_func[341]: USB OUT==>
000: D7 03 00 00 02 00 20 95 07 00 00 00 C3 03 00 00 | ...... .........
010: 00 00 00 00 3C 3F 78 6D 6C 20 76 65 72 73 69 6F | ....<?xml versio
020: 6E 3D 22 31 2E 30 22 20 65 6E 63 6F 64 69 6E 67 | n="1.0" encoding
030: 3D 22 55 54 46 2D 38 22 3F 3E 0A 3C 75 70 64 61 | ="UTF-8"?>.<upda
040: 74 65 5F 64 61 74 61 5F 6C 69 73 74 3E 0A 3C 72 | te_data_list>.<r
050: 65 67 69 6F 6E 20 69 64 3D 22 65 75 22 3E 0A 3C | egion id="eu">.<
060: 6E 70 20 6C 65 76 65 6C 30 5F 73 79 73 74 65 6D | np level0_system
070: 5F 76 65 72 73 69 6F 6E 3D 22 30 31 2E 36 30 30 | _version="01.600
080: 2E 30 30 30 22 20 6C 65 76 65 6C 31 5F 73 79 73 | .000" level1_sys
090: 74 65 6D 5F 76 65 72 73 69 6F 6E 3D 22 30 32 2E | tem_version="02.
0A0: 31 30 30 2E 30 30 30 22 20 6C 65 76 65 6C 32 5F | 100.000" level2_
0B0: 73 79 73 74 65 6D 5F 76 65 72 73 69 6F 6E 3D 22 | system_version="
0C0: 30 32 2E 31 30 30 2E 30 30 30 22 20 6D 61 70 3D | 02.100.000" map=
0D0: 22 30 31 2E 38 30 30 2E 30 30 30 22 20 2F 3E 0A | "01.800.000" />.
0E0: 3C 76 65 72 73 69 6F 6E 20 73 79 73 74 65 6D 5F | <version system_
0F0: 76 65 72 73 69 6F 6E 3D 22 30 32 2E 31 31 30 2E | version="02.110.
100: 30 30 30 22 20 6C 61 62 65 6C 3D 22 32 2E 31 31 | 000" label="2.11
110: 22 3E 0A 3C 75 70 64 61 74 65 5F 64 61 74 61 20 | ">.<update_data
120: 75 70 64 61 74 65 5F 74 79 70 65 3D 22 66 75 6C | update_type="ful
130: 6C 22 3E 0A 3C 69 6D 61 67 65 20 73 69 7A 65 3D | l">.<image size=
140: 22 31 31 39 30 31 39 35 32 30 22 3E 68 74 74 70 | "119019520">http
150: 3A 2F 2F 64 65 75 30 31 2E 70 73 70 32 2E 75 70 | ://deu01.psp2.up
160: 64 61 74 65 2E 70 6C 61 79 73 74 61 74 69 6F 6E | date.playstation
170: 2E 6E 65 74 2F 75 70 64 61 74 65 2F 70 73 70 32 | .net/update/psp2
180: 2F 69 6D 61 67 65 2F 32 30 31 33 5F 30 34 31 35 | /image/2013_0415
190: 2F 72 65 6C 5F 31 31 33 31 63 62 35 36 30 66 65 | /rel_1131cb560fe
1A0: 35 38 33 65 32 36 62 65 39 30 37 37 30 38 35 37 | 583e26be90770857
1B0: 62 35 63 31 38 2F 50 53 50 32 55 50 44 41 54 2E | b5c18/PSP2UPDAT.
1C0: 50 55 50 3F 64 65 73 74 3D 65 75 3C 2F 69 6D 61 | PUP?dest=eu</ima
1D0: 67 65 3E 0A 3C 2F 75 70 64 61 74 65 5F 64 61 74 | ge>.</update_dat
1E0: 61 3E 0A 3C 2F 76 65 72 73 69 6F 6E 3E 0A 3C 72 | a>.</version>.<r
1F0: 65 63 6F 76 65 72 79 20 73 70 6B 67 5F 74 79 70 | ecovery spkg_typ
VitaMTP ptp_write_func[341]: USB OUT==>
000: 65 3D 22 73 79 73 74 65 6D 64 61 74 61 22 3E 0A | e="systemdata">.
010: 3C 69 6D 61 67 65 20 73 70 6B 67 5F 76 65 72 73 | <image spkg_vers
020: 69 6F 6E 3D 22 30 31 2E 30 30 30 2E 30 31 30 22 | ion="01.000.010"
030: 20 73 69 7A 65 3D 22 35 36 32 36 35 37 32 38 22 |  size="56265728"
040: 3E 68 74 74 70 3A 2F 2F 64 65 75 30 31 2E 70 73 | >http://deu01.ps
050: 70 32 2E 75 70 64 61 74 65 2E 70 6C 61 79 73 74 | p2.update.playst
060: 61 74 69 6F 6E 2E 6E 65 74 2F 75 70 64 61 74 65 | ation.net/update
070: 2F 70 73 70 32 2F 69 6D 61 67 65 2F 32 30 31 33 | /psp2/image/2013
080: 5F 30 34 31 35 2F 73 64 5F 35 33 34 63 61 32 30 | _0415/sd_534ca20
090: 37 35 30 33 38 63 37 37 34 65 65 31 66 32 63 35 | 75038c774ee1f2c5
0A0: 62 37 30 39 38 39 35 62 34 2F 50 53 50 32 55 50 | b709895b4/PSP2UP
0B0: 44 41 54 2E 50 55 50 3F 64 65 73 74 3D 65 75 3C | DAT.PUP?dest=eu<
0C0: 2F 69 6D 61 67 65 3E 0A 3C 2F 72 65 63 6F 76 65 | /image>.</recove
0D0: 72 79 3E 0A 3C 72 65 63 6F 76 65 72 79 20 73 70 | ry>.<recovery sp
0E0: 6B 67 5F 74 79 70 65 3D 22 70 72 65 69 6E 73 74 | kg_type="preinst
0F0: 22 3E 0A 3C 69 6D 61 67 65 20 73 70 6B 67 5F 76 | ">.<image spkg_v
100: 65 72 73 69 6F 6E 3D 22 30 31 2E 30 30 30 2E 30 | ersion="01.000.0
110: 30 30 22 20 73 69 7A 65 3D 22 31 32 38 32 38 35 | 00" size="128285
120: 36 39 36 22 3E 68 74 74 70 3A 2F 2F 64 65 75 30 | 696">http://deu0
130: 31 2E 70 73 70 32 2E 75 70 64 61 74 65 2E 70 6C | 1.psp2.update.pl
140: 61 79 73 74 61 74 69 6F 6E 2E 6E 65 74 2F 75 70 | aystation.net/up
150: 64 61 74 65 2F 70 73 70 32 2F 69 6D 61 67 65 2F | date/psp2/image/
160: 32 30 31 33 5F 30 34 31 35 2F 70 72 65 5F 31 34 | 2013_0415/pre_14
170: 64 66 37 63 32 62 38 34 39 66 36 65 33 35 37 33 | df7c2b849f6e3573
180: 63 63 37 66 38 30 31 31 61 62 63 64 65 63 2F 50 | cc7f8011abcdec/P
190: 53 50 32 55 50 44 41 54 2E 50 55 50 3F 64 65 73 | SP2UPDAT.PUP?des
1A0: 74 3D 65 75 3C 2F 69 6D 61 67 65 3E 0A 3C 2F 72 | t=eu</image>.</r
1B0: 65 63 6F 76 65 72 79 3E 0A 3C 2F 72 65 67 69 6F | ecovery>.</regio
1C0: 6E 3E 0A 3C 2F 75 70 64 61 74 65 5F 64 61 74 61 | n>.</update_data
1D0: 5F 6C 69 73 74 3E 0A                            | _list>.  
VitaMTP ptp_usb_getresp[801]: RESPONSE: VitaMTP ptp_read_func[199]: Remaining size to read: 0x0200 bytes
VitaMTP ptp_read_func[218]: Reading in 0x0200 bytes
VitaMTP ptp_read_func[227]: Result of read: 0x0000 (16 bytes)
VitaMTP ptp_read_func[232]: <==USB IN
00: 10 00 00 00 03 00 01 20 07 00 00 00 00 00 00 00 | ....... ........
VitaMTP ptp_usb_getresp[828]: 2001
VitaMTP ptp_usb_sendreq[519]: REQUEST: 0x9518, Unknown (9518)
VitaMTP ptp_write_func[341]: USB OUT==>
00: 14 00 00 00 01 00 18 95 08 00 00 00 01 00 00 00 | ................
10: 01 20 00 00                                     | . ..  
VitaMTP ptp_usb_getresp[801]: RESPONSE: VitaMTP ptp_read_func[199]: Remaining size to read: 0x0200 bytes
VitaMTP ptp_read_func[218]: Reading in 0x0200 bytes
VitaMTP ptp_read_func[227]: Result of read: 0x0000 (12 bytes)
VitaMTP ptp_read_func[232]: <==USB IN
0: 0C 00 00 00 03 00 01 20 08 00 00 00             | ....... ....  
VitaMTP ptp_usb_getresp[828]: 2001
VitaMTP: PTP: reading event an error 0x02ff occurred
vitaEventListener: Error reading event from USB interrupt.

**Comment by jianonline** [comment]
me too

**Comment by yifanlu** [comment]
This has been fixed in the latest commit. Please wait for the next binary release if you are unwilling to compile it yourselves.
