### ISSUE TITLE
Let the PS Vita thinking to talk to the PS3 (improvement)

### ISSUE THREAD

**Issue by wargio** [yifanlu/VitaMTP#24]
This will make the PS Vita thinking to talk with a ps3..
obviously it will fail later because of an unimplemented function

```
init_info->platformType = strdup("PS3");
init_info->platformSubtype = strdup("Unknown");
init_info->osVersion = strdup("4.11");
```

**Comment by yifanlu** [comment]
I know this, but what would be the purpose?

**Comment by wargio** [comment]
find what changes from PC CMA and PS3 CMA

**Comment by yifanlu** [comment]
Sorry? There isn't any feature difference between PS3 CMA and PC CMA. It would be confusing to the user if they tap the "PS3" button and connect with the pc.

**Comment by wargio** [comment]
There are some differences: on PC everything related to APPS gets encrypted. on PS3 not. i'm interested to see if i'm able to let the PS Vita think that the PC is the PS3. in that way, maybe i can simply copy my stuff from the PSP to the PS Vita without needing the PS3.

**Comment by yifanlu** [comment]
Really? I do not have a ps3 and don't know this. Can you message me some files you've obtained?

**Comment by wargio** [comment]
well, right now. i haven't obtained any files from the vita, since the app calls the 10th vitamtp cmd (9 if you start counting from 0) that isn't implemented. i will buy a usb dumper to give a look to the usb ps3 data.
i think that it is probably something like: yes i gave you the user permission to read the HDD and modify files.

**Comment by yifanlu** [comment]
I've seen people with jailbroken ps3s dump the folders created by ps3 CMA and the contents didn't look that much different.

**Comment by wargio** [comment]
i will do some research on that. i'll mark it as closed, then if i will have new things to share, i will write you an email.
