### ISSUE TITLE
VitaMTP: cannot open usb

### ISSUE THREAD

**Issue by Ezekiel000** [yifanlu/VitaMTP#28]
I compiled VitaMTP from master on Debian Wheezy amd64, it compiled, packaged & installed fine. But when I run opencma with my vita plugged in I get VitaMTP: cannot open usb.

Log (opencma -p ./photos -v ./videos -m ./music -a ./apps -l 4):
OpenCMA 1.1 Beta
libVitaMTP Version: 2.0
Protocol Max Version: 01500010
Once connected, send SIGTSTP (usually Ctrl+Z) to refresh the database.
main: Waiting for Vita to connect...
connect_usb: Looking for USB device...
connect_usb: No Vita found. Attempt 1 of 10.
connect_usb: No Vita found. Attempt 2 of 10.
connect_usb: No Vita found. Attempt 3 of 10.
connect_usb: No Vita found. Attempt 4 of 10.
VitaMTP: cannot open usb
connect_usb: No Vita found. Attempt 5 of 10.
VitaMTP: cannot open usb
connect_usb: No Vita found. Attempt 6 of 10.
VitaMTP: cannot open usb
connect_usb: No Vita found. Attempt 7 of 10.
VitaMTP: cannot open usb
connect_usb: No Vita found. Attempt 8 of 10.
VitaMTP: cannot open usb
connect_usb: No Vita found. Attempt 9 of 10.
VitaMTP: cannot open usb
connect_usb: No Vita found. Attempt 10 of 10.
main: Error connecting.

**Comment by yifanlu** [comment]
When you compile it yourself, you are responsible for getting udev working. If you don't know how, take a look at the ubuntu deb packages to see what's being installed.
